name: 'User Reinstatement'
author: 'Brett Logan'
description: 'Automates the reinstatement of users team membership'
inputs:
  authorizers:
    description: The entry.actor from the audit log whose entries are allowed to be used
    required: true
  org:
    description: The GitHub org
    required: true
    default: ${{ github.repository_owner }}
  token:
    description: GitHub Admin PAT to open issues and comment
    required: true
runs:
  using: node20
  main: dist/index.js
